name: "PR Response Bot"
on:
  pull_request:
    types: [opened, edited]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run bot response script
        run: node bot-response.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}